@echo off
echo 🚀 Starting Fashion Era MongoDB Backend...
echo.
echo Stopping any existing Node.js processes...
taskkill /f /im node.exe >nul 2>&1
echo.
echo Starting MongoDB-powered backend server...
echo 📍 Connecting to MongoDB Atlas...
echo 💾 All user data will be stored persistently
echo.
node mongodb-backend.cjs
pause